CircleCI Delivery

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,39 +1,86 @@
-version: 2
+version: 2.1
+
+workflows:
+  version: 2
+  commit:
+    jobs:
+      - test:
+          context: circleci-user
+  build_daily:
+    triggers:
+      - schedule:
+          cron: "0 0 * * *"
+          filters:
+            branches:
+              only:
+                - master
+    jobs:
+      - test:
+          context: circleci-user
+
+orbs:
+  slack: circleci/slack@3.4.2
+
+commands:
+  run_test:
+    description: Runs a particular tap tester test
+    parameters:
+      file:
+        type: string
+    steps:
+      - run:
+          when: always
+          name: Testing << parameters.file >>
+          command: |
+            source dev_env.sh
+            source /usr/local/share/virtualenvs/tap-tester/bin/activate
+            PYTHONPATH=$PYTHONPATH:/tmp/venv/lib/python3.5/site-packages/ \
+            echo run-test --tap=tap-square \
+                     --target=target-stitch \
+                     --orchestrator=stitch-orchestrator \
+                     --email=harrison+sandboxtest@stitchdata.com \
+                     --password=$SANDBOX_PASSWORD \
+                     --client-id=50 \
+                     tests/test_<< parameters.file >>.py
 
 jobs:
-  queue:
+  test:
     docker:
-      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/deployment-utils:0.latest
+      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/tap-tester:feature.circleci-delivery
     steps:
-      - run: deployment_utils queue
-  build:
-    docker:
-      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:tap-tester-v4
-    steps:
+      - run: mkdir -p /tmp/circleci_workspace
+      - run: aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/deployment-utils/feature.global-queue/docker.env /tmp/circleci_workspace/deployment-utils.docker.env
+      - setup_remote_docker
+      - run:
+          command: |
+            docker run --rm \
+              --env-file /tmp/circleci_workspace/deployment-utils.docker.env \
+              218546966473.dkr.ecr.us-east-1.amazonaws.com/deployment-utils:feature.global-queue \
+              queue --global || {
+                echo 'Failed to queue' >&2
+                exit 1
+            }
+
       - checkout
-      - add_ssh_keys
+      - restore_cache:
+          key: venv-v1-{{ checksum "setup.py" }}
       - run:
           name: 'Setup virtual env'
           command: |
-            python3 -m venv /usr/local/share/virtualenvs/tap-square
-            source /usr/local/share/virtualenvs/tap-square/bin/activate
+            python3 -m venv /tmp/venv
+            source /tmp/venv/bin/activate
             pip install --upgrade pip
             pip install .[dev]
       - run:
           name: 'pylint tap'
           command: |
-            source /usr/local/share/virtualenvs/tap-square/bin/activate
+            source /tmp/venv/bin/activate
             pylint tap_square -d 'broad-except,chained-comparison,empty-docstring,fixme,invalid-name,line-too-long,missing-class-docstring,missing-function-docstring,missing-module-docstring,no-else-raise,no-else-return,too-few-public-methods,too-many-arguments,too-many-branches,too-many-lines,too-many-locals,ungrouped-imports,wrong-spelling-in-comment,wrong-spelling-in-docstring,too-many-public-methods'
-      #- run:
-      #    name: 'pylint tests'
-      #    command: |
-      #      source /usr/local/share/virtualenvs/tap-square/bin/activate
-      #      pylint tests -d 'broad-except,chained-comparison,empty-docstring,fixme,invalid-name,line-too-long,missing-class-docstring,missing-function-docstring,missing-module-docstring,no-else-raise,no-else-return,too-few-public-methods,too-many-arguments,too-many-branches,too-many-lines,too-many-locals,ungrouped-imports,wrong-spelling-in-comment,wrong-spelling-in-docstring,duplicate-code,no-name-in-module,attribute-defined-outside-init'
       - run:
           name: 'JSON Validator'
           command: |
             source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            stitch-validate-json /usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/tap_square/schemas/*.json
+            stitch-validate-json /tmp/venv/lib/python3.5/site-packages/tap_square/schemas/*.json
       - run:
           when: always
           name: 'Integration Tests Setup'
@@ -45,152 +92,34 @@ jobs:
           command: |
             source dev_env.sh
             source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
+            PYTHONPATH=$PYTHONPATH:/tmp/venv/lib/python3.5/site-packages/ \
             python tests/test_config.py
+      - run_test: {file: 'discovery'}
+      - run_test: {file: 'sync_canary'}
+      - run_test: {file: 'automatic_fields'}
+      - run_test: {file: 'all_fields'}
+      - run_test: {file: 'bookmarks'}
+      - run_test: {file: 'bookmarks_static'}
+      - run_test: {file: 'start_date'}
+      - run_test: {file: 'pagination'}
+      - run_test: {file: 'payments'}
       - run:
           when: always
-          name: 'Testing Discovery'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_discovery.py
+          command: docker pull 218546966473.dkr.ecr.us-east-1.amazonaws.com/deployment-utils:feature.global-queue
       - run:
           when: always
-          name: 'Testing Sync Canary'
           command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_sync_canary.py
-      - run:
-          when: always
-          name: 'Testing Automatic Fields'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_automatic_fields.py
-      - run:
-          when: always
-          name: 'Testing Schema and All Fields'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_all_fields.py
-      - run:
-          when: always
-          name: 'Testing Bookmarks for Dynamic Data Streams'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_bookmarks.py
-      - run:
-          when: always
-          name: 'Testing Bookmarks for Static Data Streams'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_bookmarks_static.py
-      - run:
-          when: always
-          name: 'Testing Start Date'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_start_date.py
-      - run:
-          when: always
-          name: 'Testing Pagination'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_pagination.py
-      - run:
-          when: always
-          name: 'Testing Payments Stream'
-          command: |
-            source dev_env.sh
-            source /usr/local/share/virtualenvs/tap-tester/bin/activate
-            PYTHONPATH=$PYTHONPATH:/usr/local/share/virtualenvs/tap-square/lib/python3.5/site-packages/ \
-            run-test --tap=tap-square \
-                     --target=target-stitch \
-                     --orchestrator=stitch-orchestrator \
-                     --email=harrison+sandboxtest@stitchdata.com \
-                     --password=$SANDBOX_PASSWORD \
-                     --client-id=50 \
-                     tests/test_payments.py
-workflows:
-  version: 2
-  commit:
-    jobs:
-      - queue:
-          context: circleci-user
-      - build:
-          context: circleci-user
-          requires:
-            - queue
-  build_daily:
-    triggers:
-      - schedule:
-          cron: "0 0 * * *"
-          filters:
-            branches:
-              only:
-                - master
-    jobs:
-      - build:
-          context: circleci-user
+            docker run \
+              --env-file /tmp/circleci_workspace/deployment-utils.docker.env \
+              218546966473.dkr.ecr.us-east-1.amazonaws.com/deployment-utils:feature.global-queue \
+              unlock --global
+      - save_cache:
+          key: venv-v1-{{ checksum "setup.py" }}
+          paths:
+            - /tmp/venv
+      - slack/status:
+          channel: '#project-${CIRCLE_PROJECT_REPONAME}'
+          mentions: "${CIRCLE_USERNAME}"
+          fail_only: true
+          failure_message: ':boom: ${CIRCLE_SHA1} tests failed!'
+         
